### ISSUE TITLE
Callbacks for zoom and pan

### ISSUE THREAD

**Issue by zhujy8833** [anvaka/three.map.control#2]
Hi,
One question about the control, are there callbacks available for zooming and panning. I need to add some logics and behaviors when zooming in/out, so a callback for it will be helpful for any customization.
Do you consider something like this would be ok?

``` javascript
createPanZoom(camera, container)
  .on('zoomend', function() { /*something to do after zoomend */ })
  .on('dragend', function() { /*something to do after zoomend */ });
```

**Comment by anvaka** [comment]
I documented officially supported events in the [readme](https://github.com/anvaka/three.map.control#events) and added `beforepan`, `beforezoom` events. Should be available in version `1.5.0`

You can also open dev console [on a demo page](https://anvaka.github.io/three.map.control/demo/), and see events being logged there.

**Comment by zhujy8833** [comment]
@anvaka Thanks for the quick action. I notice it is still missing `zoomend` since we now have `panstart`, `panend`, `beforezoom`. I guess I could still able to identify a zoom behavior by looking at `beforezoom`, but it would be beneficial to have a `zoomend`, probably right after this: https://github.com/anvaka/three.map.control/blob/master/index.js#L331.

**Comment by zhujy8833** [comment]
submitted a PR: https://github.com/anvaka/three.map.control/pull/3
@anvaka please 👀
