### ISSUE TITLE
Touch events' attributes: offsetX and offsetY are not defined (anymore)?

### ISSUE THREAD

**Issue by phuwin1995** [anvaka/three.map.control#4]
I replaced all the `offsetX` and `offsetY` attributes with `clientX` and `clientY` and it works for touch devices.

**Comment by anvaka** [comment]
Thank you for reporting this. I changed `offset` to `client` and published this package under `1.6.0`. Does this fix the bug?

**Comment by phuwin1995** [comment]
It does. Thanks for your awesome work!
